[package]
name = "husky-rs"
version = "0.0.1"
edition = "2021"
description = "husky for cargo"
repository = "https://github.com/pplmx/husky-rs"
homepage = "https://github.com/pplmx/husky-rs"
readme = "README.md"
license = "MIT"
build = "build.rs"

[build-dependencies]
thiserror = "^1.0"

[dev-dependencies]
tempfile = "^3.13"
assert_cmd = "^2.0"
predicates = "^3.1"
