name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --all-features --workspace --exclude-files 'src/bin/*' --out xml --output-dir coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: coverage/cobertura.xml
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
