name: Husky Rs Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v6
                with:
                    fetch-depth: 0

            -   name: Extract Release Notes from CHANGELOG
                id: extract_release_notes
                uses: ffurrer2/extract-release-notes@v3
                with:
                    changelog_file: CHANGELOG.md

            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v3
                with:
                    body: ${{ steps.extract_release_notes.outputs.release_notes }}
